language: julia
os:
  - linux
julia:
  - 1.0
  - nightly
notifications:
  email: false
#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("KahanSummation"); Pkg.test("KahanSummation"; coverage=true)';
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
  - julia -e 'using Pkg; ps=Pkg.PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps); include(joinpath("docs", "make.jl"))';
